# Generated by Django 4.1 on 2023-02-09 20:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_alter_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                related_name="blogpost_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
