# Generated by Django 4.1 on 2023-02-10 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0004_message_likes"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="likes",),
        migrations.AddField(
            model_name="message",
            name="like",
            field=models.ManyToManyField(
                related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
